version: "3.8"
services:
    frontend:
       container_name: ng-docker-prod
       restart: on-failure
       build:
           context: .
           dockerfile: ./compose/Dockerfile
       ports:
           - "4200:80"
       stdin_open: true
       tty: true